version: '3.7'
services: 
  postgres_database:
    image: postgres
    restart: always
    env_file: .env.dev
    ports: 
      - 5432:5432
    volumes: 
      - pg_data:/var/lib/postgresql/data
  api_server:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    image: go-app-store:1.0
    env_file: .env.dev
    volumes: 
      - .:/go/src/store
    depends_on:
      - postgres_database
    ports:
      - 8080:8080
volumes:
  pg_data:
    driver: local
    